# Generated by Django 3.1 on 2023-04-30 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='account',
            old_name='is_adminsuperadmin',
            new_name='is_superadmin',
        ),
    ]
